#!/usr/bin/env php
<?php

define('APP_ROOT_DIR', getcwd() . '/');
define('APP_PROJECT_NAMESPACE','RTTA');
define('APP_FUNCTIONAL_TESTS_NAMESPACE','TestsFunctional');

define('APP_PHPUNIT_DIR', APP_ROOT_DIR . 'vendor/phpunit/phpunit/');

use Jane\Jane;
require 'system/jane/startup.php';

/**
 * @var Jane $jane
 */

require_once APP_PHPUNIT_DIR . "phpunit";